// BLE implementation of CliTransport, using flutter_blue_plus.
//
// Wire-level contract mirrors sk_transport_ble.c + sk_secure_session.c:
//   Service UUID       : f100d001-7a5b-4c1e-8d2f-4a6b9c3e1d01
//   cmd_rx (write)     : f100d002-7a5b-4c1e-8d2f-4a6b9c3e1d01
//   event_tx (notify)  : f100d003-7a5b-4c1e-8d2f-4a6b9c3e1d01
//
// On connect (with bond / token in hand) the device emits:
//   {"evt":"auth.challenge","data":"<16-byte hex>"}
// The peer must reply with mutual challenge-response:
//   {"cmd":"auth.response","args":{"response":"<16hex>","challenge":"<16hex>"}}
// where `response` = HMAC-SHA256(token, device_challenge)[:16] and
// `challenge` is a fresh 16-byte random value generated by the peer.
// The device then verifies the response and replies:
//   {"ok":true,"data":{"answer":"<16hex>"}}
// where `answer` = HMAC-SHA256(token, peer_challenge)[:16]. The peer
// validates `answer`; once it matches the channel is `authenticated`
// and ready for signed-envelope CLI traffic.

import 'dart:async';
import 'dart:convert';
import 'dart:math';
import 'dart:typed_data';

import 'package:convert/convert.dart';
import 'package:crypto/crypto.dart';
import 'package:flutter/foundation.dart' show debugPrint, kDebugMode;
import 'package:flutter_blue_plus/flutter_blue_plus.dart';

import '../ble/paired_ble_scanner.dart' show beginBleExclusive, endBleExclusive;
import '../pairing/pairing_link.dart'
    show NdjsonLineBuffer, PairingLineOverflow;
import 'cli_transport.dart';

const _svcUuid = 'f100d001-7a5b-4c1e-8d2f-4a6b9c3e1d01';
const _cmdRxUuid = 'f100d002-7a5b-4c1e-8d2f-4a6b9c3e1d01';
const _eventTxUuid = 'f100d003-7a5b-4c1e-8d2f-4a6b9c3e1d01';

/// Cihaz tarafı `{"evt":"pairing.required","data":{"reason":"no_bond"}}`
/// notify ettiğinde fırlatılır. Anlamı: cihaz pairing modunda, kendisinin
/// bond'u yok (factory-reset, NVS clear vb. sonrası), bizim ise bond
/// hatırımızda saklı — reconnect path'i mantıksız, pairing bootstrap akışı
/// (pairing.ecdh.exchange) gerek. pairing_screen bu exception'ı yakalayıp
/// kullanıcıya "Eşleşmeyi yenile" dialog'unu otomatik açar.
class PairingRequiredException implements Exception {
  const PairingRequiredException(this.reason);
  final String reason;

  @override
  String toString() => 'PairingRequiredException(reason=$reason)';
}

/// Diagnostik trace: BleCliTransport her adımda buraya event push eder,
/// pairing_screen abone olup ekran logunda gösterir. 8sn timeout yerine
/// kullanıcı hangi adımın takıldığını görür — auth.challenge geldi mi,
/// listener fire etti mi, parse başarılı mı.
final _bleTraceController =
    StreamController<({String message, DateTime ts})>.broadcast();

Stream<({String message, DateTime ts})> get bleTraceStream =>
    _bleTraceController.stream;

void _bleTrace(String message) {
  // Console log only in debug builds — release logcat/console must not
  // capture device-response fragments (may include the start of a
  // `mode.get` payload / auth_key). The in-app pairing trace stream stays
  // (it's the user's own device, shown transiently on the pairing screen).
  if (kDebugMode) debugPrint('[BLE] $message');
  _bleTraceController.add((message: message, ts: DateTime.now()));
}

class BleCliTransport implements CliTransport {
  BleCliTransport({required this.device, required List<int> token})
      : _token = Uint8List.fromList(token);

  // Aşama bütçeleri — TransportSelector.bleTimeout bunların toplamından
  // türetilir; teker teker değişirse invariant testi kırılır (bilinçli,
  // bkz. timeout_budget_test.dart).
  static const kDisconnectTimeout = Duration(seconds: 3);
  static const kConnectTimeout = Duration(seconds: 10);
  static const kConnectOuterTimeout = Duration(seconds: 12);
  static const kDiscoverTimeout = Duration(seconds: 8);
  static const kSubscribeTimeout = Duration(seconds: 5);
  static const kChallengeSettle = Duration(milliseconds: 200);
  static const kMtuTimeout = Duration(seconds: 5);
  static const kAuthTimeout = Duration(seconds: 8);

  /// connect()'in iç aşamalarının toplamı. Dış sarmalayıcılar bundan KISA
  /// olamaz — 15 s'lik eski TransportSelector.bleTimeout tavanı ~41 s'lik
  /// bu zinciri her yavaş bağlantıda ortadan kesiyor ve gerçek aşama
  /// bilgisini (discover'da mı kaldı?) çıplak TimeoutException'a
  /// çeviriyordu; üstelik cihazın pairing.required ipucuyla yarışıyordu.
  static Duration get connectBudget =>
      kDisconnectTimeout +
      kConnectOuterTimeout +
      kDiscoverTimeout +
      kSubscribeTimeout +
      kChallengeSettle +
      kMtuTimeout +
      kAuthTimeout;

  final BluetoothDevice device;
  final Uint8List _token;

  final _incoming = StreamController<String>.broadcast();
  final _authDone = Completer<void>();
  bool _authenticated = false;
  Uint8List? _ourChallenge;

  BluetoothCharacteristic? _cmdRx;
  BluetoothCharacteristic? _eventTx;
  StreamSubscription<List<int>>? _notifySub;
  StreamSubscription<BluetoothConnectionState>? _connSub;
  final _lineBuf = NdjsonLineBuffer();

  @override
  Stream<String> get incoming => _incoming.stream;

  @override
  bool get authenticated => _authenticated;

  @override
  Future<void> connect() async {
    // Her BLE çağrısı sessizce bloklanabilir (cihazın crash'i,
    // characteristic discovery'nin Android tarafında hang etmesi vs.).
    // Tek tek timeout sararak UI'nin "deniyor…" sonsuza kadar dönmesini
    // engelliyoruz; tüm timeout'lar peer-tarafının kötü davranışına
    // karşı savunma, başarılı yolda hepsi <500 ms.
    //
    // Akış sırası (KRİTİK): connect → discover → subscribe → kısa bekle →
    // MTU exchange. MTU exchange'i auth handshake'inin SONUNA bıraktık;
    // çünkü Android tarafında requestMtu, link katmanını geçici olarak
    // resetliyor ve BF on_subscribe callback'inde anında yayınlanan
    // auth.challenge notify'ı bu pencerede kayboluyordu. auth.challenge
    // ~50 byte olduğundan default 23 MTU ile fragmente girse bile
    // güvenle iletilir. MTU yükseltmesi sadece sonraki signed envelope
    // trafiği için gerekli, handshake için değil.
    //
    // beginBleExclusive: connect süresince PairedBleScanner'ın 30sn'lik
    // periyodik scan'inin tetiklenmesini bloke et. Concurrent scan +
    // connect Android'de adapter state machine'ini bozar (auth.challenge
    // notify pipe'ı çakılır).
    beginBleExclusive();
    try {
      // Eslesme bootstrap linki yeni kapandiysa Android ayni handle uzerinde
      // yarim-acik bir baglanti tutup yeni connect'i saniyelerce stall
      // edebiliyor (eslesme -> wifi gecisindeki timeout'un asil sebebi).
      // Once kisa bir defensive disconnect ile temizle; zaten bagli degilse
      // no-op, maliyeti yok.
      try {
        await device.disconnect().timeout(kDisconnectTimeout);
      } catch (e) {
        _bleTrace('pre-connect disconnect: $e (zaten bagli degil, devam)');
      }
      _bleTrace('connect: GAP connect → ${device.remoteId.str}');
      await device
          .connect(
            timeout: kConnectTimeout,
            license: License.free,
            autoConnect: false,
          )
          .timeout(kConnectOuterTimeout);
      _bleTrace('connect: GAP connected');

      // Kopuş algılama: BLE linki düşerse (cihaz reboot, menzil) bekleyen
      // istekler 10 s'lik komut timeout'unu beklemek yerine anında
      // TransportClosedException alsın diye incoming'e hata düşürüp
      // kapanıyoruz. connectionState listen ilk emisyonda mevcut durumu
      // (connected) verir; yalnız disconnected'a tepki veririz.
      _connSub = device.connectionState.listen((s) {
        if (s == BluetoothConnectionState.disconnected) {
          _bleTrace('link dropped (GAP disconnected)');
          if (!_incoming.isClosed) {
            _incoming.addError(const TransportClosedException('BLE link dropped'));
          }
          close();
        }
      });

      _bleTrace('discover: services');
      final services =
          await device.discoverServices().timeout(kDiscoverTimeout);
      _bleTrace('discover: ${services.length} services');
      final svc = services.firstWhere(
        (s) => s.uuid.str.toLowerCase() == _svcUuid,
        orElse: () => throw StateError('SKAPP GATT service not found'),
      );
      _cmdRx = svc.characteristics.firstWhere(
        (c) => c.uuid.str.toLowerCase() == _cmdRxUuid,
        orElse: () => throw StateError('cmd_rx characteristic not found'),
      );
      _eventTx = svc.characteristics.firstWhere(
        (c) => c.uuid.str.toLowerCase() == _eventTxUuid,
        orElse: () => throw StateError('event_tx characteristic not found'),
      );
      _bleTrace('discover: SKAPP svc + cmd_rx + event_tx OK');

      // Listen ÖNCE attach edilmeli, aksi halde setNotifyValue ile listen
      // arasında BF tarafının yayınladığı auth.challenge kaybolabilir.
      _notifySub = _eventTx!.onValueReceived.listen(_onNotify);
      _bleTrace('subscribe: listener attached, enabling CCCD');
      await _eventTx!.setNotifyValue(true).timeout(kSubscribeTimeout);
      _bleTrace('subscribe: CCCD enabled, awaiting auth.challenge');

      // BF on_subscribe → sk_secure_session_begin → notify yayını arası
      // tipik olarak <50 ms. 200ms tampon: auth.challenge'ın stream'e
      // düşmesi ve _onNotify dispatch'inin başlamasına süre tanır.
      await Future.delayed(kChallengeSettle);

      // MTU yükseltmesini auth handshake'inin sonuna taşıdık.
      try {
        await device.requestMtu(247).timeout(kMtuTimeout);
        _bleTrace('MTU exchange OK (target 247)');
      } catch (e) {
        _bleTrace('MTU exchange failed ($e), default ATT');
      }

      // Device sends auth.challenge as soon as a bonded peer connects.
      // 8s is generous, typical handshake completes in <500 ms.
      _bleTrace('await auth handshake (${kAuthTimeout.inSeconds}s timeout)');
      await _authDone.future.timeout(kAuthTimeout);
      _bleTrace('auth handshake OK');
    } finally {
      endBleExclusive();
    }
  }

  void _onNotify(List<int> chunk) {
    _bleTrace('rx ${chunk.length}B');
    final List<String> lines;
    try {
      lines = _lineBuf.feed(utf8.decode(chunk, allowMalformed: true));
    } on PairingLineOverflow catch (e) {
      // İ-10: `\n` göndermeyen uç tamponu sınırsız büyütür. Bağlantıyı kes.
      _bleTrace('$e — link kapatılıyor');
      if (!_authDone.isCompleted) {
        _authDone.completeError(TransportClosedException(e));
      }
      if (!_incoming.isClosed) _incoming.addError(e);
      close();
      return;
    }
    for (final line in lines) {
      // Only trace the raw line preview in debug; in release just note that
      // a line arrived so the pairing UI still shows progress without
      // surfacing response content.
      _bleTrace(kDebugMode
          ? 'rx line: ${line.length > 60 ? '${line.substring(0, 60)}…' : line}'
          : 'rx line (${line.length} B)');
      _handleLine(line);
    }
  }

  Future<void> _handleLine(String line) async {
    if (line.isEmpty) return;
    Map<String, dynamic> msg;
    try {
      msg = jsonDecode(line) as Map<String, dynamic>;
    } catch (_) {
      // Handshake sırasında bozuk/kesik notify sıfır izle kayboluyordu ve
      // asıl sebep (fragmentasyon/MTU) 8 s jenerik timeout'a dönüşüyordu.
      _bleTrace('rx malformed line dropped (${line.length}B)');
      return;
    }

    if (!_authenticated) {
      // Phase 0: pairing-mode hint from device.
      //
      // Cihaz "ben pairing modundayım, bond'um yok" diye haber gönderiyor.
      // Reconnect path bizi 8 sn auth.challenge beklemeye düşürür ve "Bad
      // state" soft transient'a uğrarız; sonra kullanıcı pairing dialog'unu
      // hiç görmeden Tekrar dene'de sonsuza kadar döner. Bu hint sayesinde
      // _authDone'u hemen PairingRequired exception'ı ile fail ediyoruz;
      // pairing_screen hard rejection branch'ine düşer ve dialog otomatik
      // açılır.
      if (msg['evt'] == 'pairing.required') {
        final data = msg['data'];
        final reason = (data is Map && data['reason'] is String)
            ? data['reason'] as String
            : 'no_bond';
        _bleTrace('pairing.required hint received (reason=$reason)');
        if (!_authDone.isCompleted) {
          _authDone.completeError(PairingRequiredException(reason));
        }
        return;
      }

      // Phase 1: device challenge → mutual response
      if (msg['evt'] == 'auth.challenge') {
        _bleTrace('auth.challenge received, sending response');
        final hexChallenge = msg['data'] as String?;
        if (hexChallenge == null) {
          // Sessiz return _authDone'u askıda bırakıp 8 s jenerik timeout
          // üretiyordu; asıl sebep ("cihaz bozuk challenge gönderdi")
          // artık anında yüzeye çıkıyor.
          if (!_authDone.isCompleted) {
            _authDone.completeError(
                const AuthRejectedException('malformed auth.challenge'));
          }
          return;
        }
        final challenge = Uint8List.fromList(hex.decode(hexChallenge));

        // Our response = HMAC(token, deviceChallenge)[:16]
        final resp = Hmac(sha256, _token).convert(challenge).bytes.sublist(0, 16);

        // Generate our own 16-byte challenge for the device to answer.
        _ourChallenge = _randomBytes(16);

        final body = jsonEncode({
          'cmd': 'auth.response',
          'args': {
            'response': hex.encode(resp),
            'challenge': hex.encode(_ourChallenge!),
          },
        });
        await _writeLine(body);
        _bleTrace('auth.response sent');
        return;
      }

      // Phase 2: device's answer to our challenge
      if (msg['ok'] == true && msg['data'] is Map) {
        final data = msg['data'] as Map<String, dynamic>;
        final answerHex = data['answer'] as String?;
        if (answerHex == null || _ourChallenge == null) {
          _bleTrace('handshake: ok-frame without answer/our-challenge, '
              'ignored (answer=${answerHex != null}, '
              'ourChallenge=${_ourChallenge != null})');
          return;
        }

        final answer = Uint8List.fromList(hex.decode(answerHex));
        final expected = Hmac(sha256, _token)
            .convert(_ourChallenge!)
            .bytes
            .sublist(0, 16);

        if (_constantTimeEq(answer, expected)) {
          _authenticated = true;
          _bleTrace('mutual auth verified, channel authenticated');
          if (!_authDone.isCompleted) _authDone.complete();
        } else {
          _bleTrace('auth answer MISMATCH (token differs from BF bond)');
          if (!_authDone.isCompleted) {
            _authDone.completeError(
              const AuthRejectedException('auth answer verification failed'),
            );
          }
        }
        return;
      }

      // Anything else during handshake is unexpected (likely an error
      // envelope from the device); surface it as a normal incoming line
      // so the screen can show the err code, then bail the wait.
      if (msg['ok'] == false) {
        _incoming.add(line);
        if (!_authDone.isCompleted) {
          _authDone.completeError(
            AuthRejectedException(msg['err']?.toString() ?? 'auth rejected'),
          );
        }
        return;
      }
      _bleTrace('handshake: unexpected frame ignored');
      return;
    }

    // Authenticated traffic just goes upstream.
    _incoming.add(line);
  }

  Future<void> _writeLine(String body) async {
    final bytes = utf8.encode('$body\n');
    // Respect MTU: chunk to keep each ATT PDU within the negotiated MTU
    // (default 247 → 244 payload). 180 is a defensive floor.
    const chunkSize = 180;
    for (var i = 0; i < bytes.length; i += chunkSize) {
      final end = (i + chunkSize > bytes.length) ? bytes.length : i + chunkSize;
      await _cmdRx!.write(bytes.sublist(i, end), withoutResponse: false);
    }
  }

  Uint8List _randomBytes(int n) {
    final r = Random.secure();
    final out = Uint8List(n);
    for (var i = 0; i < n; i++) {
      out[i] = r.nextInt(256);
    }
    return out;
  }

  bool _constantTimeEq(List<int> a, List<int> b) {
    if (a.length != b.length) return false;
    var diff = 0;
    for (var i = 0; i < a.length; i++) {
      diff |= a[i] ^ b[i];
    }
    return diff == 0;
  }

  @override
  Future<void> sendLine(String line) async {
    if (_cmdRx == null) throw StateError('BLE transport not connected');
    await _writeLine(line);
  }

  @override
  Future<void> close() async {
    _authenticated = false;
    await _connSub?.cancel();
    _connSub = null;
    await _notifySub?.cancel();
    try {
      await device.disconnect();
    } catch (e) {
      _bleTrace('close: disconnect: $e'); // best-effort, zaten kopuk olabilir
    }
    if (!_incoming.isClosed) await _incoming.close();
  }
}
